apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-components-hac
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argo-cd-apps/overlays/crc
    repoURL: https://github.com/jduimovich/standalone-hac.git
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
